version: '3.7'
services:
#****************************************  backend********************************************************
  backend:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      # HOST:CONTAINER
      - "3001:3001"
    restart: on-failure
    # depends_on:
    #   - db
    container_name: back_end
#****************************************  frontend ********************************************************
  frontend:
    build: ./client
    ports:
      - "5173:3000"
    restart: on-failure
    depends_on:
      - backend
    container_name: front_end
#********************************************  database ****************************************************
  db:
    image: mysql:latest
    env_file:
      - ./server/.env
    restart: on-failure
    ports:
      # HOST:CONTAINER
      - 8080:8080
    container_name: my_db
