@hostname = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFycm1hbmk4OCIsImlkIjoxLCJpYXQiOjE2NTU0NzAyNjB9.jwbDc_qdpzlc14n7er7XU1VH8zuByKtBZ-nDNxWnCPo

### ------------------------------- REGISTER -------------------------------
POST {{hostname}}/register
Content-Type: application/json

{
    "firstname": "anas",
    "lastname": "el boudali",
    "username": "arrmani88",
    "email": "a@a.com",
    "password": "qweqwe123"
}

# username: between 2 & 35 characters, and can be alphanumeric
# password: minimum 8 characters, at least one letter
# -------------------------------------------------------------------------
### ----------------------------- LOGIN -----------------------------------
POST {{hostname}}/login
Content-Type: application/json

{
    "login": "arrmani88",
    "password": "qweqwe123"
}

# -------------------------------------------------------------------------
### -------------------------- COMPLETE PROFILE ---------------------------
POST {{hostname}}/complete_profile
Content-Type: application/json
Authorization: {{token}}

{
    "birthday": "1994-12-24",
    "gender": "M",
    "sexualPreferences": "F",
    "biography": "some dwescription ....",
    "tags": ["aaaa", "bbbb", "ccc", "dddd", "eee"]
}

# 'birthday': should be like YYYY-MM-DD
# 'gender': should be either 'M', 'F' or 'N' (if not specified)
# 'sexualPreferences': should be either 'M', 'F' or 'N' (if not specified)
# -------------------------------------------------------------------------
### ----------------------- UPLOAD PROFILE IMAGE --------------------------
POST {{hostname}}/upload_profile_image
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="158436118_1908379119318336_7678135232057492950_n.jpg"

< /Users/anel-bou/Desktop/158436118_1908379119318336_7678135232057492950_n.jpg
--boundary--
# image should be either '.jpg', '.jpeg', or '.png', and less than 1024*1024 bytes (1MB)
# -------------------------------------------------------------------------
### ------------------------- UPLOAD FEED IMAGES --------------------------
POST {{hostname}}/upload_feed_images
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="images"; filename="158436118_1908379119318336_7678135232057492950_n.jpg"
Content-Type: image/jpeg

< /Users/anel-bou/Desktop/158436118_1908379119318336_7678135232057492950_n.jpg
--boundary
Content-Disposition: form-data; name="images"; filename="158436118_1908379119318336_7678135232057492950_n.jpg"
Content-Type: image/jpeg

< /Users/anel-bou/Desktop/158436118_1908379119318336_7678135232057492950_n.jpg
--boundary--
# key-> images
# value-> between 1 and 4 images
# each image should be either '.jpg', '.jpeg', or '.png', and less than (1024*1024) bytes (1MB)
# -------------------------------------------------------------------------
### ----------------------- SEND RESET PASSWORD EMAIL ---------------------
GET {{hostname}}/reset_password
Content-Type: application/json

{
    "username": "arrmani88"
}

# -------------------------------------------------------------------------
### ---------------------------- RESET PASSWORD ---------------------------
POST {{hostname}}/reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFycm1hbmk4OCIsImlhdCI6MTY1NDY4MzM4NH0.ScWgLpm9sEQxv3cESVgjAoVRlWMH_AJri3FuLmL3HuE
Content-Type: application/json

{
    "password": "123123qwe"
}

# --------------------------------------------------------------------------
### ------------------------ UPDATE PROFILE DATA ---------------------------
POST {{hostname}}/update_profile
Authorization: {{token}}
Content-Type: application/json

{
    "newFirstname": "bb",
    "username": "arrmani88",
    "password": "qweqwe123",
    "oldTags": ["eee", "oo", "ccc", "dddd", "aaaa"],
    "newTags": ["111", "222", "333", "444"]
}

# -------------------------------------------------------------------------
